StudyCheckWeb.MvcWebUI/Areas/Administrator/Controllers/DersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudyCheck.Utilities.CustomExceptions;
using StudyCheckWeb.Business.Abstract;
using StudyCheckWeb.Entities.Concrete;
using StudyCheckWeb.MvcWebUI.Areas.Administrator.Models;
using StudyCheckWeb.MvcWebUI.Authentication;

namespace StudyCheckWeb.MvcWebUI.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [Authorize(Roles = "Admin")]
    public class DersController : Controller
    {
        IDersService _dersService;
        ISinavService _sinavService;
        IUyedetayService _uyedetayService;
        EntityListModel _entityListModel;
        UserManager<User> _userManager;

        public DersController(IDersService dersService, ISinavService sinavService, IUyedetayService uyedetayService, UserManager<User> userManager)
        {
            _dersService = dersService;
            _sinavService = sinavService;
            _uyedetayService = uyedetayService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DersDuzenle(DersModel model)
        {
            model.tumSinavlar = _sinavService.GetListByStatus(1);
            model.ekleyenKisi = _uyedetayService.GetById(model.ekleyenId).kullanici_adi;
            model.guncelleyenKisi = _uyedetayService.GetById(model.guncelleyenId).kullanici_adi;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DersDuzenle(string dersAd,int durum,int sinavId,int dersId,string kayitTarihi,int ekleyenId)
        {
            try
            {
                if (dersAd == null)
                    throw new RequiredFieldsException("Ders adı boş bırakılamaz");
                var dersler = _dersService.GetAll().Where(d => d.ders_ad == dersAd).ToList();
                if (dersler.Count > 1)
                    throw new Exception("Bu ders zaten kayıtlı");
                else
                {
                    var identityUser = await _userManager.GetUserAsync(HttpContext.User);
                    Ders updatedDers = new Ders
                    {
                        id = dersId,
                        ders_ad = dersAd,
                        eklenme_tarihi = Convert.ToDateTime(kayitTarihi),
                        ekleyen_id = ekleyenId,
                        guncelleme_tarihi = DateTime.Now,
                        guncelleyen_id = identityUser.uyeDetayId,
                        sil_id = durum,
                        sinav_id = sinavId
                    };
                    _dersService.UpdateDers(updatedDers);
                    TempData["Sonuc"] = "Ders başarıyla güncellendi";
                }
            }
            catch (Exception ex)
            {
                TempData["Exception"] = ex.Message;
            }
            return RedirectToAction("DersListesi");
        }

        public IActionResult DersListesi()
        {
            _entityListModel = new EntityListModel
            {
                kullanicilar = _uyedetayService.GetAll(),
                dersler = _dersService.GetAll(),
                sinavlar = _sinavService.GetAll()
            };
            if (TempData["Sonuc"] != null)
                ViewBag.Message = TempData["Sonuc"].ToString();
            if (TempData["Exception"] != null)
                ViewBag.Exceptions = TempData["Exception"].ToString();
            return View(_entityListModel);
        }

        public IActionResult DersEkle()
        {
            _entityListModel = new EntityListModel
            {
                sinavlar = _sinavService.GetListByStatus(1)
            };
            return View(_entityListModel);
        }

        [HttpPost]
        public async Task<IActionResult> DersEkle(string dersAd,int durum,int sinavId)
        {
            try
            {
                if (dersAd == null)
                    throw new RequiredFieldsException("Ders adı boş geçilemez!");

                var ders = _dersService.GetAll().Where(d => d.ders_ad.ToLower() == dersAd.ToLower()).FirstOrDefault();
                if (ders != null)
                    throw new Exception("Bu ders zaten kayıtlı");
                else
                {
                    var identityUser = await _userManager.GetUserAsync(HttpContext.User);
                    Ders dersimiz = new Ders
                    {
                        sinav_id = sinavId,
                        ders_ad = dersAd,
                        eklenme_tarihi = DateTime.Now,
                        ekleyen_id = identityUser.uyeDetayId,
                        guncelleme_tarihi = DateTime.Now,
                        sil_id = durum,
                        guncelleyen_id = identityUser.uyeDetayId
                    };
                    _dersService.AddDers(dersimiz);
                    ViewBag.Message = "Ders başarıyla eklendi";
                }
            }
            catch (Exception ex)
            {
                ViewBag.Exceptions = ex.Message;
            }
            _entityListModel = new EntityListModel
            {
                sinavlar = _sinavService.GetListByStatus(1)
            };
            return View(_entityListModel);
        }
    }
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Ders/DersDuzenle.cshtml
@model DersModel
@{
    ViewData["Title"] = "Ders Düzenle";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Ders Düzenle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Ders İşlemleri</a></li>
                    <li class="breadcrumb-item active">Ders Düzenle</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">Ders Bilgileri</h3>
                    </div>
                    <!-- /.card-header -->
                    <form method="post">
                        <div class="card-body">
                            <div class="row align-items-start">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Ders Adı</label>
                                        <input name="dersAd" type="text" class="form-control" placeholder="Ders adı..." value="@Model.dersAd">
                                    </div>
                                    <div class="form-group">
                                        <label>Durum</label>
                                        <select name="durum" class="form-control select2 select2-success" data-dropdown-css-class="select2-success" style="width: 100%;">
                                            @{
                                                if (Model.silId == 1)
                                                {
                                                    <option value="1" selected>Aktif</option>
                                                    <option value="0">Pasif</option>
                                                }
                                                else if (Model.silId == 0)
                                                {
                                                    <option value="1">Aktif</option>
                                                    <option value="0" selected>Pasif</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Kayıtlı olduğu sınav</label>
                                        <select name="sinavId" class="form-control select2 select2-primary" data-dropdown-css-class="select2-primary" style="width: 100%;">
                                            @foreach (var sinav in Model.tumSinavlar)
                                            {
                                                if (Model.sinavId == sinav.id)
                                                {
                                                    <option value="@sinav.id" selected>@sinav.sinav_ad</option>
                                                }
                                                else
                                                {
                                                    <option value="@sinav.id">@sinav.sinav_ad</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="row align-items-center">
                                <div class="col col-md-6">
                                    <a asp-area="administrator" asp-controller="ders" asp-action="dersListesi"><i class="fas fa-window-close" style="font-size:xx-large"></i></a>
                                </div>
                                <div class="col col-md-6">
                                    <button type="submit" class="btn btn-success float-md-right"><i class="fas fa-save"></i> Kaydet</button>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <input type="hidden" name="dersId" value="@Model.dersId" />
                        <input type="hidden" name="kayitTarihi" value="@Model.eklenmeTarihi" />
                        <input type="hidden" name="ekleyenId" value="@Model.ekleyenId" />
                    </form>
                </div>
            </div>
            <!-- right column -->
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><b>Kayıt Bilgileri</b></h3>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><b style="color:#ff5311">Ders Id:</b> @Model.dersId</li>
                        <li class="list-group-item"><b style="color:#ff5311">Son Güncelleme Tarihi:</b> @Model.guncellemeTarihi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Kayıt Tarihi:</b> @Model.eklenmeTarihi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Rolü Ekleyen:</b> @Model.ekleyenKisi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Son Güncelleyen:</b> @Model.guncelleyenKisi</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts{
    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });
        })
    </script>
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Ders/DersEkle.cshtml
@model EntityListModel
@{
    ViewData["Title"] = "Ders Ekle";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Ders Ekle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Ders İşlemleri</a></li>
                    <li class="breadcrumb-item active">Ders Ekle</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">Ders Bilgileri</h3>
                    </div>
                    <!-- /.card-header -->
                    <form role="form" method="post">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Ders Adı</label>
                                <input name="dersAd" type="text" class="form-control" placeholder="Ders adı...">
                            </div>
                            <div class="form-group">
                                <label>Durum</label>
                                <select name="durum" class="form-control select2 select2-success" data-dropdown-css-class="select2-success" style="width: 100%;">
                                    <option value="1" selected="selected">Aktif</option>
                                    <option value="0">Pasif</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Hangi Sınav</label>
                                <select name="sinavId" class="form-control select2 select2-warning" data-dropdown-css-class="select2-warning" style="width: 100%;">
                                    @foreach (var sinav in Model.sinavlar)
                                    {
                                        <option value="@sinav.id">@sinav.sinav_ad</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Ekle</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@if (ViewBag.Exceptions != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Exceptions", "exception");
    </script>
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Message", "success");
    </script>
}

@section Scripts{
    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });
        })
    </script>
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Ders/DersListesi.cshtml
@model EntityListModel;
@{
    ViewData["Title"] = "Ders Listesi";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
    DersModel _model;
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>
    <!-- Utilities -->
    <script src="~/scripts/adminPanel/Utilities.js"></script>
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Ders Listesi</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Ders İşlemleri</a></li>
                    <li class="breadcrumb-item active">Ders Listesi</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tüm Dersler</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="dersTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Ders Id</th>
                                <th>Ders Adı</th>
                                <th>Kayıtlı Olduğu Sınav</th>
                                <th>Kayıt Tarihi</th>
                                <th>Dersi Ekleyen</th>
                                <th>Durum</th>
                                <th class="text-center">İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var ders in Model.dersler)
                            {
                                _model = new DersModel
                                {
                                    dersAd = ders.ders_ad,
                                    dersId = ders.id,
                                    eklenmeTarihi = ders.eklenme_tarihi,
                                    ekleyenId = ders.ekleyen_id,
                                    guncellemeTarihi = ders.guncelleme_tarihi,
                                    guncelleyenId = ders.guncelleyen_id,
                                    silId = ders.sil_id,
                                    sinavId = ders.sinav_id
                                };
                                <tr>
                                    <td class="text-center" style="color:#ff5311;">@ders.id</td>
                                    <td>@ders.ders_ad</td>
                                    <td>@Model.sinavlar.Where(s => s.id == ders.sinav_id).Single().sinav_ad</td>
                                    <td>@ders.eklenme_tarihi</td>
                                    <td>@Model.kullanicilar.Where(k => k.id == ders.ekleyen_id).Single().kullanici_adi</td>
                                    <td style="@(ders.sil_id==0 ? "color:red;":"color:limegreen;")">@(ders.sil_id==1?"Aktif":"Pasif")</td>
                                    <td class="text-center" style="color:#ff5311;"><a href="@Url.Action("DersDuzenle","Ders",_model)"><i class="fas fa-cog"></i></a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</section>

@if (ViewBag.Exceptions != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Exceptions", "exception");
    </script>
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Message", "success");
    </script>
}

@section Scripts{
    <!-- DataTables -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(function () {
            $("#dersTable").DataTable({
                "language": {
                    "info": "Toplam: _TOTAL_ veri mevcut",
                    "infoEmpty": "Gösterilecek veri yok",
                    "infoFiltered": " - _MAX_ veriden filtrelendi",
                    "lengthMenu": "Göster _MENU_ Roller",
                    "search": "Ara:",
                    "zeroRecords": "Kayıt bulunamadı",
                    "paginate": {
                        "previous": "Önceki",
                        "next": "Sonraki"
                    },
                },
                "responsive": true,
                "autoWidth": false,
                "paging": true,
            });
        });
    </script>
}