StudyCheckWeb.MvcWebUI/Areas/Administrator/Controllers/SinavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using StudyCheck.Utilities.CustomExceptions;
using StudyCheckWeb.Business.Abstract;
using StudyCheckWeb.Entities.Concrete;
using StudyCheckWeb.MvcWebUI.Areas.Administrator.Models;
using StudyCheckWeb.MvcWebUI.Authentication;

namespace StudyCheckWeb.MvcWebUI.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [Authorize(Roles = "Admin")]
    public class SinavController : Controller
    {
        IUyedetayService _uyedetayService;
        ISinavService _sinavService;
        IDersService _dersService;
        EntityListModel _entityListModel;
        UserManager<User> _userManager;

        public SinavController(IUyedetayService uyedetayService, ISinavService sinavService, UserManager<User> userManager, IDersService dersService)
        {
            _uyedetayService = uyedetayService;
            _sinavService = sinavService;
            _userManager = userManager;
            _dersService = dersService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SinavDuzenle(SinavModel model)
        {
            model.guncelleyenKisi = _uyedetayService.GetById(model.guncelleyenId).kullanici_adi;
            model.ekleyenKisi = _uyedetayService.GetById(model.ekleyenId).kullanici_adi;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SinavDuzenle(string sinavAd,string sinavTarihi,int sinavId,string eklenmeTarihi,int ekleyenId,int durum)
        {
            try
            {
                if (sinavAd == null || sinavTarihi == null)
                    throw new RequiredFieldsException("Sınav bilgileri boş bırakılamaz");

                var sinav = _sinavService.GetAll().Where(s => s.sinav_ad == sinavAd).ToList();
                if(durum == 0)
                {
                    var sinavDers = _dersService.GetListBySinavId(sinavId);
                    if (sinavDers.Count > 0)
                        throw new Exception("Bu sınavı kullanan dersler var");
                }

                if (sinav.Count > 1)
                    throw new Exception("Bu sınav zaten kayıtlı");
                else
                {
                    var identityUser = await _userManager.GetUserAsync(HttpContext.User);
                    Sinav updatedSinav = new Sinav
                    {
                        id = sinavId,
                        sinav_tarih = Convert.ToDateTime(sinavTarihi),
                        eklenme_tarihi = Convert.ToDateTime(eklenmeTarihi),
                        ekleyen_id = ekleyenId,
                        guncelleme_tarihi = DateTime.Now,
                        guncelleyen_id = identityUser.uyeDetayId,
                        sil_id = durum,
                        sinav_ad = sinavAd
                    };
                    _sinavService.UpdateSinav(updatedSinav);
                    TempData["Sonuc"] = "Sınav başarıyla güncellendi";
                }
            }
            catch (Exception ex)
            {
                TempData["Exception"] = ex.Message;
            }
            return RedirectToAction("SinavListesi");
        }

        public IActionResult SinavListesi()
        {
            _entityListModel = new EntityListModel
            {
                sinavlar = _sinavService.GetAll(),
                kullanicilar = _uyedetayService.GetAll()
            };
            if (TempData["Sonuc"] != null)
                ViewBag.Message = TempData["Sonuc"].ToString();
            if (TempData["Exception"] != null)
                ViewBag.Exceptions = TempData["Exception"].ToString();
            return View(_entityListModel);
        }

        public IActionResult SinavEkle()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SinavEkle(string sinavAdi,int durum,string sinavTarihi)
        {
            try
            {
                if (sinavAdi == null)
                    throw new RequiredFieldsException("Sınav adı boş bırakılamaz");
                if(sinavTarihi == null)
                    throw new RequiredFieldsException("Sınav tarihi boş bırakılamaz");

                var sinav = _sinavService.GetAll().Where(s => s.sinav_ad.ToLower() == sinavAdi.ToLower()).FirstOrDefault();
                if (sinav != null)
                    throw new Exception("Bu sınav zaten kayıtlı");
                else
                {
                    var identityUser = await _userManager.GetUserAsync(HttpContext.User);
                    Sinav sinavimiz = new Sinav
                    {
                        sinav_ad = sinavAdi,
                        sinav_tarih = Convert.ToDateTime(sinavTarihi),
                        eklenme_tarihi = DateTime.Now,
                        ekleyen_id = identityUser.uyeDetayId,
                        guncelleme_tarihi = DateTime.Now,
                        sil_id = durum,
                        guncelleyen_id = identityUser.uyeDetayId
                    };
                    _sinavService.AddSinav(sinavimiz);
                    ViewBag.Message = "Sınav başarıyla eklendi";
                }
            }
            catch (Exception ex)
            {
                ViewBag.Exceptions = ex.Message;
            }
            return View();
        }
    }
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Sinav/SinavDuzenle.cshtml
@model SinavModel
@{
    ViewData["Title"] = "Sınav Düzenle";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}


<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Sınav Düzenle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Sınav İşlemleri</a></li>
                    <li class="breadcrumb-item active">Sınav Düzenle</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">Sınav Bilgileri</h3>
                    </div>
                    <!-- /.card-header -->
                    <form method="post">
                        <div class="card-body">
                            <div class="row align-items-start">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Sınav Adı</label>
                                        <input name="sinavAd" type="text" class="form-control" placeholder="Sınav adı..." value="@Model.sinavAd">
                                    </div>
                                    <div class="form-group">
                                        <label>Durum</label>
                                        <select name="durum" class="form-control select2 select2-success" data-dropdown-css-class="select2-success" style="width: 100%;">
                                            @{
                                                if (Model.silId == 1)
                                                {
                                                    <option value="1" selected>Aktif</option>
                                                    <option value="0">Pasif</option>
                                                }
                                                else if (Model.silId == 0)
                                                {
                                                    <option value="1">Aktif</option>
                                                    <option value="0" selected>Pasif</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Sınav Tarihi</label>
                                        <!-- buraya-->
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                            </div>
                                            <input name="sinavTarihi" type="text" class="form-control" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask value="@Model.sinavTarihi">
                                        </div>
                                        <!-- /.input group -->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="row align-items-center">
                                <div class="col col-md-6">
                                    <a asp-area="administrator" asp-controller="sinav" asp-action="sinavListesi"><i class="fas fa-window-close" style="font-size:xx-large"></i></a>
                                </div>
                                <div class="col col-md-6">
                                    <button type="submit" class="btn btn-success float-md-right"><i class="fas fa-save"></i> Kaydet</button>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <input type="hidden" name="sinavId" value="@Model.sinavId" />
                        <input type="hidden" name="eklenmeTarihi" value="@Model.eklenmeTarihi" />
                        <input type="hidden" name="ekleyenId" value="@Model.ekleyenId" />
                    </form>
                </div>
            </div>
            <!-- right column -->
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><b>Kayıt Bilgileri</b></h3>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><b style="color:#ff5311">Sınav Id:</b> @Model.sinavId</li>
                        <li class="list-group-item"><b style="color:#ff5311">Son Güncelleme Tarihi:</b> @Model.guncellemeTarihi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Kayıt Tarihi:</b> @Model.eklenmeTarihi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Sınavı Ekleyen:</b> @Model.ekleyenKisi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Son Güncelleyen:</b> @Model.guncelleyenKisi</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>
    <!-- InputMask -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>

    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });
            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
            //Money Euro
            $('[data-mask]').inputmask()//input mask için gerekli
        })
    </script>
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Sinav/SinavEkle.cshtml
@{
    ViewData["Title"] = "Sınav Ekle";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Sınav Ekle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Sınav İşlemleri</a></li>
                    <li class="breadcrumb-item active">Sınav Ekle</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">Sınav Bilgileri</h3>
                    </div>
                    <!-- /.card-header -->
                    <form asp-area="administrator" asp-controller="sinav" method="post">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Sınav Adı</label>
                                <input name="sinavAdi" type="text" class="form-control" placeholder="Sınav adı...">
                            </div>
                            <div class="form-group">
                                <label>Durum</label>
                                <select name="durum" class="form-control select2 select2-success" data-dropdown-css-class="select2-success" style="width: 100%;">
                                    <option selected="selected" value="1">Aktif</option>
                                    <option value="0">Pasif</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Sınav Tarihi</label>
                                <!-- buraya-->
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="far fa-calendar-alt"></i></span>
                                    </div>
                                    <input name="sinavTarihi" type="text" class="form-control" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask>
                                </div>
                                <!-- /.input group -->
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Ekle</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@if (ViewBag.Exceptions != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Exceptions", "exception");
    </script>
}

@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Message", "success");
    </script>
}


@section Scripts{
    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>

    <!-- InputMask -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/inputmask/min/jquery.inputmask.bundle.min.js"></script>

    <!-- Page script -->
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            })

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
            //Money Euro
            $('[data-mask]').inputmask()//input mask için gerekli

        })
    </script>
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Sinav/SinavListesi.cshtml
@model EntityListModel;
@{
    ViewData["Title"] = "Sınav Listesi";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
    SinavModel _model;
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>
    <!-- Utilities -->
    <script src="~/scripts/adminPanel/Utilities.js"></script>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Sınav Listesi</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Sınav İşlemleri</a></li>
                    <li class="breadcrumb-item active">Sınav Listesi</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tüm Roller</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="sinavTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Sınav Id</th>
                                <th>Sınav Adı</th>
                                <th>Sınav Tarihi</th>
                                <th>Kayıt Tarihi</th>
                                <th>Sınavı Ekleyen</th>
                                <th>Durum</th>
                                <th class="text-center">İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var sinav in Model.sinavlar)
                            {
                                _model = new SinavModel
                                {
                                    sinavId = sinav.id,
                                    eklenmeTarihi = sinav.eklenme_tarihi,
                                    sinavAd = sinav.sinav_ad,
                                    ekleyenId = sinav.ekleyen_id,
                                    guncellemeTarihi = sinav.guncelleme_tarihi,
                                    guncelleyenId = sinav.guncelleyen_id,
                                    silId = sinav.sil_id,
                                    sinavTarihi = sinav.sinav_tarih
                                };
                                <tr>
                                    <td class="text-center" style="color:#ff5311;">@sinav.id</td>
                                    <td>@sinav.sinav_ad</td>
                                    <td>@sinav.sinav_tarih.ToShortDateString()</td>
                                    <td>@sinav.eklenme_tarihi</td>
                                    <td>@Model.kullanicilar.Where(k => k.id == sinav.ekleyen_id).Single().kullanici_adi</td>
                                    <td style="@(sinav.sil_id==0?"color:red;":"color:limegreen;")">@(sinav.sil_id == 1?"Aktif":"Pasif")</td>
                                    <td class="text-center" style="color:#ff5311;"><a href="@Url.Action("SinavDuzenle","Sinav",_model)"><i class="fas fa-cog"></i></a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</section>


@if (ViewBag.Exceptions != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Exceptions", "exception");
    </script>
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Message", "success");
    </script>
}

@section Scripts{
    <!-- DataTables -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(function () {
            $("#sinavTable").DataTable({
                "language": {
                    "info": "Toplam: _TOTAL_ veri mevcut",
                    "infoEmpty": "Gösterilecek veri yok",
                    "infoFiltered": " - _MAX_ veriden filtrelendi",
                    "lengthMenu": "Göster _MENU_ Sınavlar",
                    "search": "Ara:",
                    "zeroRecords": "Kayıt bulunamadı",
                    "paginate": {
                        "previous": "Önceki",
                        "next": "Sonraki"
                    },
                },
                "responsive": true,
                "autoWidth": false,
                "paging": true,
            });
        });
    </script>
}