StudyCheckWeb.MvcWebUI/Areas/Administrator/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudyCheck.Utilities.CustomExceptions;
using StudyCheckWeb.Business.Abstract;
using StudyCheckWeb.DataAccess.Abstract;
using StudyCheckWeb.DataAccess.Concrete.EntityFramework.Contexts;
using StudyCheckWeb.Entities.Concrete;
using StudyCheckWeb.MvcWebUI.Areas.Administrator.Models;
using StudyCheckWeb.MvcWebUI.Authentication;

namespace StudyCheckWeb.MvcWebUI.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [Authorize(Roles = "Admin")]
    public class KullaniciController : Controller
    {
        IUyeService _uyeService;
        IRolService _rolService;
        IUyedetayService _uyedetayService;
        UserManager<User> _userManager;
        EntityListModel _entityListModel;
        SenkronizasyonModel _model;

        public KullaniciController(IUyeService uyeService, IRolService rolService, IUyedetayService uyedetayService, UserManager<User> userManager)
        {
            _uyeService = uyeService;
            _rolService = rolService;
            _uyedetayService = uyedetayService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult KullaniciDuzenle(KullaniciModel model)
        {
            model.tumRoller = _rolService.GetListByStatus(1);
            model.guncelleyenKisi = _uyedetayService.GetById(model.guncelleyenId).kullanici_adi;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> KullaniciDuzenle(string uyeDetayId,string uyeId,string kayitTarihi,string kullaniciAdi, string sifre, string mail, int durum, int rol, string uyeAd, string uyeSoyad)
        {
            try
            {
                if (uyeAd == null || uyeSoyad == null)
                    throw new RequiredFieldsException("Üye bilgileri boş bırakılamaz!");
                else if (kullaniciAdi == null || sifre == null || mail == null)
                    throw new RequiredFieldsException("Kullanıcı bilgileri boş bırakılamaz!");
                var kullanici = _uyedetayService.GetAll().Where(k => k.kullanici_adi == kullaniciAdi || k.kullanici_mail == mail).ToList();
                if (kullanici.Count > 1)
                    throw new Exception("Bu kullanıcı adı / mail zaten mevcut!");
                else
                {
                    using (StudyCheckContext context = new StudyCheckContext())
                    {
                        using (var transaction = context.Database.BeginTransaction())
                        {
                            try
                            {
                                var oldUser = _uyedetayService.GetById(Convert.ToInt32(uyeDetayId));
                                var updatedUser =await _userManager.FindByNameAsync(oldUser.kullanici_adi);
                                if(oldUser.kullanici_sifre != sifre)
                                {
                                    IdentityResult passResult = await _userManager.ChangePasswordAsync(updatedUser, oldUser.kullanici_sifre, sifre);
                                    if (!passResult.Succeeded)
                                        throw new Exception(passResult.Errors.First().Description);
                                }                                                                                                    
                                updatedUser.UserName = kullaniciAdi;
                                updatedUser.NormalizedUserName = kullaniciAdi.ToUpper();
                                updatedUser.Email = mail;
                                updatedUser.NormalizedEmail = mail.ToUpper();
                                updatedUser.uyeAdi = uyeAd;
                                updatedUser.uyeSoyadi = uyeSoyad;
                                updatedUser.kullaniciAdi = kullaniciAdi;
                                updatedUser.kullaniciSifre = sifre;
                                updatedUser.kullaniciMail = mail;
                                updatedUser.rolId = rol;                                
                                IdentityResult result = await _userManager.UpdateAsync(updatedUser);
                                if (!result.Succeeded)
                                    throw new Exception(result.Errors.First().Description);
                                else
                                {
                                    Uye updatedUye = new Uye
                                    {
                                        id = Convert.ToInt32(uyeId),
                                        uye_ad = uyeAd,
                                        uye_soyad = uyeSoyad
                                    };
                                    context.Uyeler.Update(updatedUye);
                                    context.SaveChanges();
                                    var identityUser = await _userManager.GetUserAsync(HttpContext.User);
                                    Uyedetay updatedKullanici = new Uyedetay
                                    {
                                        id = Convert.ToInt32(uyeDetayId),
                                        kullanici_adi = kullaniciAdi,
                                        kullanici_sifre = sifre,
                                        kullanici_mail = mail,
                                        kayit_tarihi = Convert.ToDateTime(kayitTarihi),
                                        guncelleyen_id = identityUser.uyeDetayId,
                                        guncelleme_tarihi = DateTime.Now,
                                        uye_id = Convert.ToInt32(uyeId),
                                        rol_id = rol,
                                        tema_id = 1,
                                        sil_id = durum
                                    };
                                    context.UyeDetay.Update(updatedKullanici);
                                    context.SaveChanges();
                                }
                                
                            }
                            catch (Exception transException)
                            {
                                transaction.Rollback();
                                throw new Exception(transException.Message);
                            }
                            TempData["Sonuc"] = "Kullanıcı güncellendi";                            
                            transaction.Commit();
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                TempData["Exception"] = ex.Message;                
            }
            return RedirectToAction("KullaniciListesi");
        }

        public async Task<IActionResult> KullaniciListesi()
        {
            var userDetails = _uyeService.GetAllUserDetail();            
            _entityListModel = new EntityListModel
            {
                UserDetails = userDetails,
                roller = _rolService.GetAll(),
                senkron = new List<SenkronizasyonModel>()
            };            
            foreach (var user in userDetails)
            {
                var identity = await _userManager.FindByNameAsync(user.kullanici_adi);
                if (identity == null)
                {
                    _model = new SenkronizasyonModel
                    {
                        senkronUsername = user.kullanici_adi,
                        senkron = 0
                    };
                    _entityListModel.senkron.Add(_model);
                }
                else
                {
                    _model = new SenkronizasyonModel
                    {
                        senkronUsername = user.kullanici_adi,
                        senkron = 1
                    };
                    _entityListModel.senkron.Add(_model);
                }
            }
            if (TempData["Exception"] != null)
                ViewBag.Exceptions = TempData["Exception"].ToString();
            if (TempData["Sonuc"] != null)
                ViewBag.Message = TempData["Sonuc"].ToString();
            return View(_entityListModel);
        }
        public IActionResult KullaniciEkle()
        {
            _entityListModel = new EntityListModel
            {
                roller = _rolService.GetListByStatus(1)
            };
            return View(_entityListModel);
        }

        [HttpPost]
        public async Task<IActionResult> KullaniciEkle(string kullaniciAdi,string sifre,string mail,int durum,int rol,string uyeAd,string uyeSoyad)
        {
            try
            {
                if (kullaniciAdi == null || sifre == null || mail == null)
                    throw new RequiredFieldsException("Kullanıcı bilgileri boş bırakılamaz!");
                else if (uyeAd == null || uyeSoyad == null)
                    throw new RequiredFieldsException("Üye bilgileri boş bırakılamaz!");

                var user = _uyedetayService.GetAll().Where(k => k.kullanici_adi == kullaniciAdi || k.kullanici_mail == mail).FirstOrDefault();//uyedetay tablosunda var mı
                if (user != null)//var
                    throw new Exception("Bu kullanıcı adı / mail zaten mevcut!");
                else //yok
                {
                    using (StudyCheckContext context = new StudyCheckContext())
                    {
                        using (var transaction = context.Database.BeginTransaction())
                        {
                            try
                            {
                                Uye uyemiz = new Uye
                                {

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Kullanici/KullaniciEkle.cshtml
@model EntityListModel
@{
    ViewData["Title"] = "Kullanıcı Ekle";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>
    <!-- Utilities -->
    <script src="~/scripts/adminPanel/Utilities.js"></script>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Kullanıcı Ekle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Kullanıcı İşlemleri</a></li>
                    <li class="breadcrumb-item active">Kullanıcı Ekle</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">Kullanıcı Bilgileri</h3>
                    </div>
                    <!-- /.card-header -->
                    <form asp-area="Administrator" asp-controller="Kullanici" method="post">
                        <div class="card-body">
                            <div class="row align-items-start">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Üye Adı</label>
                                        <input name="uyeAd" type="text" class="form-control" placeholder="Üye adı...">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Üye Soyadı</label>
                                        <input name="uyeSoyad" type="text" class="form-control" placeholder="Üye soyadı...">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Kullanıcı Adı</label>
                                        <input name="kullaniciAdi" type="text" class="form-control" placeholder="Kullanıcı adı...">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Şifre</label>
                                        <input id="pass" name="sifre" type="password" class="form-control" placeholder="Şifre...">
                                    </div>
                                    <div class="form-group">
                                        <div class="icheck-primary d-inline">
                                            <input type="checkbox" id="showPass">
                                            <label for="showPass">
                                                Şifreyi Göster
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Kullanıcı Mail</label>
                                        <input name="mail" type="email" class="form-control" placeholder="Mail...">
                                    </div>
                                    <div class="form-group">
                                        <label>Durum</label>
                                        <select name="durum" class="form-control select2 select2-success" data-dropdown-css-class="select2-success" style="width: 100%;">
                                            <option value="1">Aktif</option>
                                            <option value="0">Pasif</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Tema</label>
                                        <select class="form-control select2 select2-warning" data-dropdown-css-class="select2-warning" style="width: 100%;">
                                            <option selected="selected">Default</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Rol</label>
                                        <select name="rol" class="form-control select2 select2-primary" data-dropdown-css-class="select2-primary" style="width: 100%;">
                                            @foreach (var rol in Model.roller)
                                            {
                                                <option value="@rol.id">@rol.rol_adi</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Ekle</button>
                        </div>
                        <!-- /.card-body -->
                    </form>
                </div>
            </div>
            <!-- right column -->
        </div>
    </div>
</section>

@if (ViewBag.Exceptions != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Exceptions", "exception");
    </script>
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Message", "message");
    </script>
}

@section Scripts{
    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });
        })
    </script>
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Kullanici/KullaniciListesi.cshtml
@model EntityListModel;
@{
    ViewData["Title"] = "Kullanıcı Listesi";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
    KullaniciModel _model;
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>    
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Kullanıcı Listesi</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Kullanıcı İşlemleri</a></li>
                    <li class="breadcrumb-item active">Kullanıcı Listesi</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tüm Kullanıcılar</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="kullaniciTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Uye Id</th>
                                <th>Uye Adı</th>
                                <th>Uye Soyadı</th>
                                <th>Kullanıcı Adı</th>
                                <th>E-Mail</th>
                                <th>Kayıt Tarihi</th>
                                <th>Rol (in Desktop)</th>
                                <th>Durum</th>
                                <th class="text-center">İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.UserDetails)
                            {
                                _model = new KullaniciModel
                                {
                                    uyeId = item.uye_id,
                                    uyeDetayId = item.uyedetay_id,
                                    uyeAd = item.uye_ad,
                                    uyeSoyad = item.uye_soyad,
                                    kullaniciAdi = item.kullanici_adi,
                                    kullaniciSifre = item.kullanici_sifre,
                                    kullaniciMail = item.kullanici_mail,
                                    kayitTarihi = item.kayit_tarihi,
                                    guncellemeTarihi = item.guncelleme_tarihi,
                                    silId = item.sil_id,
                                    rolId = item.rol_id,
                                    guncelleyenId = item.guncelleyen_id
                                };
                                if (Model.senkron.Find(s => s.senkronUsername == item.kullanici_adi).senkron == 1)
                                {
                                    <tr>
                                        <td class="text-center" style="color:#ff5311;">@item.uye_id</td>
                                        <td>@item.uye_ad</td>
                                        <td>@item.uye_soyad</td>
                                        <td>@item.kullanici_adi</td>
                                        <td>@item.kullanici_mail</td>
                                        <td>@item.kayit_tarihi</td>
                                        <td>@Model.roller.Where(r => r.id == item.rol_id).Single().rol_adi</td>
                                        <td style="@(item.sil_id == 0?"color:red;":"color:limegreen;")">@(item.sil_id == 1 ? "Aktif":"Pasif")</td>
                                        <td class="text-center"><a href="@Url.Action("KullaniciDuzenle","Kullanici",_model)"><i style="color:#ff5311;" class="fas fa-cog"></i></a></td>
                                    </tr>
                                }
                                else
                                {
                                    <tr>
                                        <td class="text-center" style="color:#ff5311;">@item.uye_id</td>
                                        <td>@item.uye_ad</td>
                                        <td>@item.uye_soyad</td>
                                        <td>@item.kullanici_adi</td>
                                        <td>@item.kullanici_mail</td>
                                        <td>@item.kayit_tarihi</td>
                                        <td>@Model.roller.Where(r => r.id == item.rol_id).Single().rol_adi</td>
                                        <td style="@(item.sil_id == 0?"color:red;":"color:limegreen;")">@(item.sil_id == 1 ? "Aktif":"Pasif")</td>
                                        <td class="text-center" style="background:#ffd800">Hesap Senkronize Değil</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</section>

@if (ViewBag.Exceptions != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Exceptions", "exception");
    </script>
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Message", "success");
    </script>
}

@section Scripts{
    <!-- DataTables -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(function () {
            $("#kullaniciTable").DataTable({
                "language": {
                    "info": "Toplam _TOTAL_ veri mevcut.",
                    "infoEmpty": "Gösterilecek veri yok",
                    "infoFiltered": " - _MAX_ veriden filtrelendi",
                    "lengthMenu": "Göster _MENU_ Kullanıcılar",
                    "search": "Ara:",
                    "zeroRecords": "Kayıt bulunamadı",
                    "paginate": {
                        "previous": "Önceki",
                        "next": "Sonraki"
                    },
                },
                "responsive": true,
                "autoWidth": false,
                "paging": true,
            });
        });
    </script>
}