StudyCheckWeb.MvcWebUI/Areas/Administrator/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudyCheck.Utilities.CustomExceptions;
using StudyCheckWeb.Business.Abstract;
using StudyCheckWeb.Entities.Concrete;
using StudyCheckWeb.MvcWebUI.Areas.Administrator.Models;
using StudyCheckWeb.MvcWebUI.Authentication;

namespace StudyCheckWeb.MvcWebUI.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    [Authorize(Roles = "Admin")]
    public class RolController : Controller
    {
        UserManager<User> _userManager;
        IRolService _rolService;
        IUyedetayService _uyedetayService;
        IYetkiService _yetkiService;
        EntityListModel _entityListModel;        

        public RolController(IRolService rolService, IUyedetayService uyedetayService, IYetkiService yetkiService, UserManager<User> userManager)
        {
            _rolService = rolService;
            _uyedetayService = uyedetayService;
            _yetkiService = yetkiService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RolDuzenle(RolModel model)
        {
            model.tumYetkiler = _yetkiService.GetListByStatus(1);
            model.ekleyenKisi = _uyedetayService.GetById(model.ekleyenId).kullanici_adi;
            model.guncelleyenKisi = _uyedetayService.GetById(model.guncelleyenId).kullanici_adi;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RolDuzenle(int rolId,string rolAd,int durum,int rolYetki,string kayitTarihi,int ekleyenId)
        {
            try
            {
                if (rolAd == null)
                    throw new RequiredFieldsException("Rol adı boş geçilemez");
                var roller = _rolService.GetAll().Where(r => r.rol_adi == rolAd).ToList();
                if (roller.Count > 1)
                    throw new Exception("Bu rol adı zaten kayıtlı");
                else
                {
                    var identityUser = await _userManager.GetUserAsync(HttpContext.User);
                    Rol updatedRol = new Rol
                    {
                        id = rolId,
                        ekleyen_id = ekleyenId,
                        guncelleyen_id = identityUser.uyeDetayId,
                        rol_adi = rolAd,
                        rol_guncelleme_tarihi = DateTime.Now,
                        rol_kayit_tarihi =Convert.ToDateTime(kayitTarihi),
                        sil_id = durum,
                        yetki_id = rolYetki
                    };
                    _rolService.UpdateRol(updatedRol);
                    TempData["Sonuc"] = "Rol başarıyla güncellendi";
                }
            }
            catch (Exception ex)
            {
                TempData["Exception"] = ex.Message;                
            }
            return RedirectToAction("RolListesi");
        }

        public IActionResult RolListesi()
        {
            _entityListModel = new EntityListModel
            {
                roller = _rolService.GetAll(),
                yetkiler = _yetkiService.GetAll(),
                kullanicilar = _uyedetayService.GetAll()
            };
            if (TempData["Sonuc"] != null)
                ViewBag.Message = TempData["Sonuc"].ToString();
            if(TempData["Exception"] != null)
                ViewBag.Exceptions = TempData["Exception"].ToString();
            return View(_entityListModel);
        }

        public IActionResult RolEkle()
        {
            _entityListModel = new EntityListModel
            {
                yetkiler = _yetkiService.GetListByStatus(1)
            };
            return View(_entityListModel);
        }

        [HttpPost]
        public async Task<IActionResult> RolEkle(string rolAd,int durum,int yetkiId)
        {
            try
            {
                if (rolAd == null)
                    throw new RequiredFieldsException("Rol adı boş geçilemez");

                var rol = _rolService.GetAll().Where(r => r.rol_adi.ToLower() == rolAd.ToLower()).FirstOrDefault();
                if (rol != null)
                    throw new Exception("Bu rol zaten kayıtlı");
                else
                {
                    var identityUser = await _userManager.GetUserAsync(HttpContext.User);
                    Rol rolumuz = new Rol
                    {
                        rol_adi = rolAd,
                        rol_kayit_tarihi = DateTime.Now,
                        ekleyen_id = identityUser.uyeDetayId,
                        rol_guncelleme_tarihi = DateTime.Now,
                        sil_id = durum,
                        yetki_id = yetkiId,
                        guncelleyen_id = identityUser.uyeDetayId
                    };
                    _rolService.AddRol(rolumuz);
                    ViewBag.Message = "Rol başarıyla oluşturuldu";
                }
            }
            catch (Exception ex)
            {
                ViewBag.Exceptions = ex.Message;
            }
            _entityListModel = new EntityListModel
            {
                yetkiler = _yetkiService.GetListByStatus(1)
            };
            return View(_entityListModel);
        }
    }
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Rol/RolDuzenle.cshtml
@model RolModel
@{
    ViewData["Title"] = "Rol Düzenle";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>
    <!-- Utilities -->
    <script src="~/scripts/adminPanel/Utilities.js"></script>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Rol Düzenle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Rol İşlemleri</a></li>
                    <li class="breadcrumb-item active">Rol Düzenle</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">Rol Bilgileri</h3>
                    </div>
                    <!-- /.card-header -->
                    <form method="post">
                        <div class="card-body">
                            <div class="row align-items-start">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Rol Adı</label>
                                        <input name="rolAd" type="text" class="form-control" placeholder="Rol adı..." value="@Model.rolAd">
                                    </div>
                                    <div class="form-group">
                                        <label>Durum</label>
                                        <select name="durum" class="form-control select2 select2-success" data-dropdown-css-class="select2-success" style="width: 100%;">
                                            @{
                                                if (Model.silId == 1)
                                                {
                                                    <option value="1" selected>Aktif</option>
                                                    <option value="0">Pasif</option>
                                                }
                                                else if (Model.silId == 0)
                                                {
                                                    <option value="1">Aktif</option>
                                                    <option value="0" selected>Pasif</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label>Rol Yetkisi</label>
                                        <select name="rolYetki" class="form-control select2 select2-primary" data-dropdown-css-class="select2-primary" style="width: 100%;">
                                            @foreach (var yetki in Model.tumYetkiler)
                                            {
                                                if (Model.yetkiId == yetki.id)
                                                {
                                                    <option value="@yetki.id" selected>@yetki.yetki_adi</option>
                                                }
                                                else
                                                {
                                                    <option value="@yetki.id">@yetki.yetki_adi</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="row align-items-center">
                                <div class="col col-md-6">
                                    <a asp-area="administrator" asp-controller="rol" asp-action="rolListesi"><i class="fas fa-window-close" style="font-size:xx-large"></i></a>
                                </div>
                                <div class="col col-md-6">
                                    <button type="submit" class="btn btn-success float-md-right"><i class="fas fa-save"></i> Kaydet</button>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <input type="hidden" name="rolId" value="@Model.rolId" />
                        <input type="hidden" name="kayitTarihi" value="@Model.kayitTarihi" />
                        <input type="hidden" name="ekleyenId" value="@Model.ekleyenId" />                        
                    </form>
                </div>
            </div>
            <!-- right column -->
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><b>Kayıt Bilgileri</b></h3>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><b style="color:#ff5311">Rol Id:</b> @Model.rolId</li>
                        <li class="list-group-item"><b style="color:#ff5311">Son Güncelleme Tarihi:</b> @Model.guncellemeTarihi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Kayıt Tarihi:</b> @Model.kayitTarihi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Rolü Ekleyen:</b> @Model.ekleyenKisi</li>
                        <li class="list-group-item"><b style="color:#ff5311">Son Güncelleyen:</b> @Model.guncelleyenKisi</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>



@section Scripts{
    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });
        })
    </script>
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Rol/RolEkle.cshtml
@model EntityListModel
@{
    ViewData["Title"] = "Rol Ekle";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Rol Ekle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Rol İşlemleri</a></li>
                    <li class="breadcrumb-item active">Rol Ekle</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">Rol Bilgileri</h3>
                    </div>
                    <!-- /.card-header -->
                    <form role="form" method="post">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Rol Adı</label>
                                <input name="rolAd" type="text" class="form-control" id="" placeholder="Rol adı...">
                            </div>
                            <div class="form-group">
                                <label>Durum</label>
                                <select name="durum" class="form-control select2 select2-success" data-dropdown-css-class="select2-success" style="width: 100%;">
                                    <option value="1" selected="selected">Aktif</option>
                                    <option value="0">Pasif</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Rol Yetkisi</label>
                                <select name="yetkiId" class="form-control select2 select2-warning" data-dropdown-css-class="select2-warning" style="width: 100%;">
                                    @foreach (var yetki in Model.yetkiler)
                                    {
                                        <option value="@yetki.id">@yetki.yetki_adi</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i> Ekle</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


@if (ViewBag.Exceptions != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Exceptions", "exception");
    </script>
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Message", "success");
    </script>
}

@section Scripts{
    <!-- Select2 -->
    <script src="~/plugins/select2/js/select2.full.min.js"></script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            });
        })
    </script>
}

StudyCheckWeb.MvcWebUI/Areas/Administrator/Views/Rol/RolListesi.cshtml
@model EntityListModel;
@{
    ViewData["Title"] = "Rol Listesi";
    Layout = "~/Areas/Administrator/Views/Shared/_AdminLayout.cshtml";
    RolModel _model;
}

@section AlertScripts{
    <!-- JQuery -->
    <script src="~/scripts/jquery/jquery.min.js"></script>
    <!-- Sweet Alert 2 -->
    <script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/plugins/toastr/toastr.min.js"></script>
    <!-- Alerts -->
    <script src="~/scripts/loginSignOut/validationAlerts.js"></script>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Rol Listesi</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Rol İşlemleri</a></li>
                    <li class="breadcrumb-item active">Rol Listesi</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tüm Roller</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="rolTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">Rol Id</th>
                                <th>Rol Adı</th>
                                <th>Kayıt Tarihi</th>
                                <th>Rolü Ekleyen</th>
                                <th>Rol Yetkisi</th>
                                <th>Durum</th>
                                <th class="text-center">İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var rol in Model.roller)
                            {
                                _model = new RolModel
                                {
                                    rolId = rol.id,
                                    rolAd = rol.rol_adi,
                                    ekleyenId = rol.ekleyen_id,
                                    guncellemeTarihi = rol.rol_guncelleme_tarihi,
                                    guncelleyenId = rol.guncelleyen_id,
                                    kayitTarihi = rol.rol_kayit_tarihi,
                                    silId = rol.sil_id,
                                    yetkiId = rol.yetki_id
                                };
                                <tr>
                                    <td style="color:#ff5311;" class="text-center">@rol.id</td>
                                    <td>@rol.rol_adi</td>
                                    <td>@rol.rol_kayit_tarihi</td>
                                    <td>@Model.kullanicilar.Where(k => k.id == rol.ekleyen_id).Single().kullanici_adi</td>
                                    <td>@Model.yetkiler.Where(y => y.id == rol.yetki_id).Single().yetki_adi</td>
                                    <td style="@(rol.sil_id==0?"color:red;":"color:limegreen;")">@(rol.sil_id == 1 ? "Aktif":"Pasif")</td>
                                    <td class="text-center"><a href="@Url.Action("RolDuzenle","Rol",_model)"><i style="color:#ff5311;" class="fas fa-cog"></i></a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</section>

@if (ViewBag.Exceptions != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Exceptions", "exception");
    </script>
}
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        AlertErrors("Sonuç", "@ViewBag.Message", "success");
    </script>
}

@section Scripts{
    <!-- DataTables -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(function () {
            $("#rolTable").DataTable({
                "language": {
                    "info": "Toplam: _TOTAL_ veri mevcut",
                    "infoEmpty": "Gösterilecek veri yok",
                    "infoFiltered": " - _MAX_ veriden filtrelendi",
                    "lengthMenu": "Göster _MENU_ Roller",
                    "search": "Ara:",
                    "zeroRecords": "Kayıt bulunamadı",
                    "paginate": {
                        "previous": "Önceki",
                        "next": "Sonraki"
                    },
                },
                "responsive": true,
                "autoWidth": false,
                "paging": true,
            });
        });
    </script>
}